name: Composite Actions CI

on:
  push:
    tags:
      - "*"

concurrency: new-tag
jobs:
  release:
    name: GitHub Release Job
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: compute-version
        name: Compute version
        run: |
          chmod +x ./git-compute-version.sh
          ./git-compute-version.sh
      - name: Release
        if: ${{ steps.compute-version.outputs.is-dev-version == 'false' }}
        uses: EasyDesk/action-semver-release@v0.2
        with:
          version: ${{ steps.compute-version.outputs.version }}