name: Composite Actions CI

on:
  push:
    tags:
      - "*"

concurrency: new-tag
jobs:
  release:
    name: GitHub Release Job
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compute semantic version
        id: semver
        uses: ./
      - name: Release
        if: ${{ steps.semver.outputs.should-release == 'true' }}
        uses: EasyDesk/action-semver-release@v0.2
        with:
          version: ${{ steps.semver.outputs.version }}
