  
name: Composite Actions CI

on:
  push:
    tags:
      - "*"

concurrency: new-tag
jobs:
  release:
    name: GitHub Release Job
    runs-on: ubuntu-20.04
    steps:
      - id: semver
        uses: EasyDesk/action-semver-checkout@v0.2
      - if: ${{ steps.semver.outputs.should-release == 'true' }}
        uses: EasyDesk/action-sem-ver-release@v0.2
        with:
          version: ${{ steps.semver.outputs.version }}
